//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Z21Dashboard.Shared.Dashboard.Widgets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocoControl2Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocoControl2Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Z21Dashboard.Shared.Dashboard.Widgets.LocoControl2Resources", typeof(LocoControl2Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Settings for Loco address.
        /// </summary>
        internal static string EditSettingsForLoco {
            get {
                return ResourceManager.GetString("EditSettingsForLoco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter address.
        /// </summary>
        internal static string EnterAddress {
            get {
                return ResourceManager.GetString("EnterAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        internal static string Forward {
            get {
                return ResourceManager.GetString("Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking Z21 lock state....
        /// </summary>
        internal static string InfoText {
            get {
                return ResourceManager.GetString("InfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. MY 1103.
        /// </summary>
        internal static string InputPlaceHolder {
            get {
                return ResourceManager.GetString("InputPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval (hours).
        /// </summary>
        internal static string IntervalHours {
            get {
                return ResourceManager.GetString("IntervalHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time since last service.
        /// </summary>
        internal static string LastService {
            get {
                return ResourceManager.GetString("LastService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locomotive Name.
        /// </summary>
        internal static string LocomotiveName {
            get {
                return ResourceManager.GetString("LocomotiveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark service as performed (resets service timer).
        /// </summary>
        internal static string MarkService {
            get {
                return ResourceManager.GetString("MarkService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol.
        /// </summary>
        internal static string Protocol {
            get {
                return ResourceManager.GetString("Protocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol and Speed Steps.
        /// </summary>
        internal static string ProtocolAndSpeedSteps {
            get {
                return ResourceManager.GetString("ProtocolAndSpeedSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse.
        /// </summary>
        internal static string Reverse {
            get {
                return ResourceManager.GetString("Reverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Interval.
        /// </summary>
        internal static string ServiceInterval {
            get {
                return ResourceManager.GetString("ServiceInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g., 10.
        /// </summary>
        internal static string SIPlaceholder {
            get {
                return ResourceManager.GetString("SIPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        internal static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loco Control 2.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track power off.
        /// </summary>
        internal static string TrackPwrOff {
            get {
                return ResourceManager.GetString("TrackPwrOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track power on.
        /// </summary>
        internal static string TrackPwrOn {
            get {
                return ResourceManager.GetString("TrackPwrOn", resourceCulture);
            }
        }
    }
}
