//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Z21Dashboard.Shared.Dashboard.Widgets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SpeedMeasureResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SpeedMeasureResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Z21Dashboard.Shared.Dashboard.Widgets.SpeedMeasureResources", typeof(SpeedMeasureResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cm.
        /// </summary>
        internal static string cm {
            get {
                return ResourceManager.GetString("cm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cm/s.
        /// </summary>
        internal static string cms {
            get {
                return ResourceManager.GetString("cms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance from start of sensor 1 to start of sensor 2, measured in.
        /// </summary>
        internal static string Distance1To2 {
            get {
                return ResourceManager.GetString("Distance1To2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance from start of sensor 2 to start of sensor 1, measured in.
        /// </summary>
        internal static string Distance2To1 {
            get {
                return ResourceManager.GetString("Distance2To1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit settings for speed measure.
        /// </summary>
        internal static string EditSettingsForSpeedMeasure {
            get {
                return ResourceManager.GetString("EditSettingsForSpeedMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected the same sensor as Sensor 1 and Sensor 2. That is not allowed..
        /// </summary>
        internal static string ErrorDuplicateSensors {
            get {
                return ResourceManager.GetString("ErrorDuplicateSensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum distance of a block or between to contact tracke must be at least 10 cm/4 inchs..
        /// </summary>
        internal static string ErrorMinDistance {
            get {
                return ResourceManager.GetString("ErrorMinDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inch.
        /// </summary>
        internal static string inch {
            get {
                return ResourceManager.GetString("inch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in/s.
        /// </summary>
        internal static string ins {
            get {
                return ResourceManager.GetString("ins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km/h.
        /// </summary>
        internal static string kmh {
            get {
                return ResourceManager.GetString("kmh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        internal static string Module {
            get {
                return ResourceManager.GetString("Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mph.
        /// </summary>
        internal static string mph {
            get {
                return ResourceManager.GetString("mph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to port.
        /// </summary>
        internal static string PortLowercase {
            get {
                return ResourceManager.GetString("PortLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To setup the sensors needed to measure speed, please read the section about this widget in the user manual..
        /// </summary>
        internal static string ReadGuideText {
            get {
                return ResourceManager.GetString("ReadGuideText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        internal static string Scale {
            get {
                return ResourceManager.GetString("Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string seconds {
            get {
                return ResourceManager.GetString("seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor 1.
        /// </summary>
        internal static string Sensor1 {
            get {
                return ResourceManager.GetString("Sensor1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor 2.
        /// </summary>
        internal static string Sensor2 {
            get {
                return ResourceManager.GetString("Sensor2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did not receive signal from the sensor that is to stop the measure of speed.
        /// </summary>
        internal static string TimeoutError {
            get {
                return ResourceManager.GetString("TimeoutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed mesurement.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
