//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Z21Dashboard.Shared.Dashboard.Widgets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SystemStateFullViewResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SystemStateFullViewResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Z21Dashboard.Shared.Dashboard.Widgets.SystemStateFullViewResources", typeof(SystemStateFullViewResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept LAN acc. cmds.
        /// </summary>
        internal static string AcceptLANAccCmds {
            get {
                return ResourceManager.GetString("AcceptLANAccCmds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept LAN det. cmds.
        /// </summary>
        internal static string AcceptLANDetCmds {
            get {
                return ResourceManager.GetString("AcceptLANDetCmds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept LAN loco cmds.
        /// </summary>
        internal static string AcceptLANLocoCmds {
            get {
                return ResourceManager.GetString("AcceptLANLocoCmds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capabilities flags.
        /// </summary>
        internal static string CapabilitiesFlags {
            get {
                return ResourceManager.GetString("CapabilitiesFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central state flags.
        /// </summary>
        internal static string CentralStateFlags {
            get {
                return ResourceManager.GetString("CentralStateFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency stop.
        /// </summary>
        internal static string EmergencyStop {
            get {
                return ResourceManager.GetString("EmergencyStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended state flags.
        /// </summary>
        internal static string ExtendedStateFlags {
            get {
                return ResourceManager.GetString("ExtendedStateFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High temperature.
        /// </summary>
        internal static string HighTemperature {
            get {
                return ResourceManager.GetString("HighTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        internal static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal voltage.
        /// </summary>
        internal static string InternalVoltage {
            get {
                return ResourceManager.GetString("InternalVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main current.
        /// </summary>
        internal static string MainCurrent {
            get {
                return ResourceManager.GetString("MainCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mA.
        /// </summary>
        internal static string MilliAmpsShort {
            get {
                return ResourceManager.GetString("MilliAmpsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needs unlock code.
        /// </summary>
        internal static string NeedsUnlockCode {
            get {
                return ResourceManager.GetString("NeedsUnlockCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power lost.
        /// </summary>
        internal static string PowerLost {
            get {
                return ResourceManager.GetString("PowerLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programming current.
        /// </summary>
        internal static string ProgrammingCurrent {
            get {
                return ResourceManager.GetString("ProgrammingCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programming mode.
        /// </summary>
        internal static string ProgrammingMode {
            get {
                return ResourceManager.GetString("ProgrammingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocols.
        /// </summary>
        internal static string Protocols {
            get {
                return ResourceManager.GetString("Protocols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RailCom.
        /// </summary>
        internal static string RailCom {
            get {
                return ResourceManager.GetString("RailCom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCN-213 mode.
        /// </summary>
        internal static string RCN213Mode {
            get {
                return ResourceManager.GetString("RCN213Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short circuit.
        /// </summary>
        internal static string ShortCircuit {
            get {
                return ResourceManager.GetString("ShortCircuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Circuit (ext).
        /// </summary>
        internal static string ShortCircuitExt {
            get {
                return ResourceManager.GetString("ShortCircuitExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short circuit (int).
        /// </summary>
        internal static string ShortCircuitInt {
            get {
                return ResourceManager.GetString("ShortCircuitInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supply voltage.
        /// </summary>
        internal static string SupplyVoltage {
            get {
                return ResourceManager.GetString("SupplyVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        internal static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System State - Full.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track voltage.
        /// </summary>
        internal static string TrackVoltage {
            get {
                return ResourceManager.GetString("TrackVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V.
        /// </summary>
        internal static string VoltShort {
            get {
                return ResourceManager.GetString("VoltShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
