//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Z21Dashboard.Shared.Dashboard.Widgets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TurnoutListViewResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TurnoutListViewResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Z21Dashboard.Shared.Dashboard.Widgets.TurnoutListViewResources", typeof(TurnoutListViewResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm that you want to delete this turnout.
        /// </summary>
        internal static string ConfirmDeleteText {
            get {
                return ResourceManager.GetString("ConfirmDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction.
        /// </summary>
        internal static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divert/Red.
        /// </summary>
        internal static string Divert {
            get {
                return ResourceManager.GetString("Divert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit settings.
        /// </summary>
        internal static string EditSettings {
            get {
                return ResourceManager.GetString("EditSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Settings for Turnout.
        /// </summary>
        internal static string EditSettingsForTurnout {
            get {
                return ResourceManager.GetString("EditSettingsForTurnout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval of switches before service.
        /// </summary>
        internal static string IntervalSwitches {
            get {
                return ResourceManager.GetString("IntervalSwitches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last changed.
        /// </summary>
        internal static string LastChanged {
            get {
                return ResourceManager.GetString("LastChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark service as performed (resets service counter).
        /// </summary>
        internal static string MarkServicePerformed {
            get {
                return ResourceManager.GetString("MarkServicePerformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol.
        /// </summary>
        internal static string Protocol {
            get {
                return ResourceManager.GetString("Protocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service in.
        /// </summary>
        internal static string ServiceIn {
            get {
                return ResourceManager.GetString("ServiceIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service interval.
        /// </summary>
        internal static string ServiceInterval {
            get {
                return ResourceManager.GetString("ServiceInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service overdue by.
        /// </summary>
        internal static string ServiceOverdueBy {
            get {
                return ResourceManager.GetString("ServiceOverdueBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straight/Green.
        /// </summary>
        internal static string Straight {
            get {
                return ResourceManager.GetString("Straight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switches.
        /// </summary>
        internal static string Switches {
            get {
                return ResourceManager.GetString("Switches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to switches.
        /// </summary>
        internal static string SwitchesPostFix {
            get {
                return ResourceManager.GetString("SwitchesPostFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switches since service.
        /// </summary>
        internal static string SwitchesSinceService {
            get {
                return ResourceManager.GetString("SwitchesSinceService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turnouts.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for turnout data....
        /// </summary>
        internal static string WaitingForData {
            get {
                return ResourceManager.GetString("WaitingForData", resourceCulture);
            }
        }
    }
}
