//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Z21Dashboard.Shared.Dashboard.Components.ProgrammingDecoder {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AddressResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AddressResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Z21Dashboard.Shared.Dashboard.Components.ProgrammingDecoder.AddressResource", typeof(AddressResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locomotive address read from decoder.
        /// </summary>
        internal static string CVRead {
            get {
                return ResourceManager.GetString("CVRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading locomotive address from decoder.
        /// </summary>
        internal static string CVReading {
            get {
                return ResourceManager.GetString("CVReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing new locomotive address to decoder.
        /// </summary>
        internal static string CVWriting {
            get {
                return ResourceManager.GetString("CVWriting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new locomotive address has been written to decoder.
        /// </summary>
        internal static string CVWritten {
            get {
                return ResourceManager.GetString("CVWritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not show again.
        /// </summary>
        internal static string DontShowAgain {
            get {
                return ResourceManager.GetString("DontShowAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note: To read or change the address of the locomotive, it must be placed on the programming track, as reading and changing address is not supported on the main track.
        /// </summary>
        internal static string InfoText {
            get {
                return ResourceManager.GetString("InfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locomotive address.
        /// </summary>
        internal static string LocoAddress {
            get {
                return ResourceManager.GetString("LocoAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New locomotive address must be filled.
        /// </summary>
        internal static string NewLocoAddressMissing {
            get {
                return ResourceManager.GetString("NewLocoAddressMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read from loco decoder.
        /// </summary>
        internal static string ReadFromLocoDecoder {
            get {
                return ResourceManager.GetString("ReadFromLocoDecoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write to loco decoder.
        /// </summary>
        internal static string WriteToLocoDecoder {
            get {
                return ResourceManager.GetString("WriteToLocoDecoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note, that you are using a z21 or z21Start that does not have a separate programming track. Hence, you are programming on the main track and all locomotives will be affected. Please remove all other locomotives..
        /// </summary>
        internal static string z21Warning {
            get {
                return ResourceManager.GetString("z21Warning", resourceCulture);
            }
        }
    }
}
