//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Z21Dashboard.Shared.Dashboard.Components.ProgrammingDecoder {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SimpleResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SimpleResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Z21Dashboard.Shared.Dashboard.Components.ProgrammingDecoder.SimpleResource", typeof(SimpleResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CV-address.
        /// </summary>
        internal static string CVAddress {
            get {
                return ResourceManager.GetString("CVAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CV read from decoder.
        /// </summary>
        internal static string CVRead {
            get {
                return ResourceManager.GetString("CVRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading CV value from decoder.
        /// </summary>
        internal static string CVReading {
            get {
                return ResourceManager.GetString("CVReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CV-value.
        /// </summary>
        internal static string CVValue {
            get {
                return ResourceManager.GetString("CVValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing CV value to decoder.
        /// </summary>
        internal static string CVWriting {
            get {
                return ResourceManager.GetString("CVWriting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CV value written to decoder.
        /// </summary>
        internal static string CVWritten {
            get {
                return ResourceManager.GetString("CVWritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locomotive address.
        /// </summary>
        internal static string LocoAddress {
            get {
                return ResourceManager.GetString("LocoAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POM.
        /// </summary>
        internal static string POM {
            get {
                return ResourceManager.GetString("POM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programming method.
        /// </summary>
        internal static string ProgMethod {
            get {
                return ResourceManager.GetString("ProgMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programming track.
        /// </summary>
        internal static string ProgTrack {
            get {
                return ResourceManager.GetString("ProgTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read from loco decoder.
        /// </summary>
        internal static string ReadFromLocoDecoder {
            get {
                return ResourceManager.GetString("ReadFromLocoDecoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programming Target is unknown.
        /// </summary>
        internal static string UnknownProgTarget {
            get {
                return ResourceManager.GetString("UnknownProgTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write to loco decoder.
        /// </summary>
        internal static string WriteToLocoDecoder {
            get {
                return ResourceManager.GetString("WriteToLocoDecoder", resourceCulture);
            }
        }
    }
}
