//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Z21Dashboard.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Z21Dashboard.Resources.Localization.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string Connection {
            get {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loco controller.
        /// </summary>
        public static string LocoControl {
            get {
                return ResourceManager.GetString("LocoControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loco controller 2.
        /// </summary>
        public static string LocoControl2 {
            get {
                return ResourceManager.GetString("LocoControl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locomotives&apos; Operating Time.
        /// </summary>
        public static string LocoListView {
            get {
                return ResourceManager.GetString("LocoListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locomotive slots.
        /// </summary>
        public static string LocoSlotView {
            get {
                return ResourceManager.GetString("LocoSlotView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power and Voltage Monitor.
        /// </summary>
        public static string PowerChart {
            get {
                return ResourceManager.GetString("PowerChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RailCom data.
        /// </summary>
        public static string RailComView {
            get {
                return ResourceManager.GetString("RailComView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R-Bus Feedback.
        /// </summary>
        public static string RBusView {
            get {
                return ResourceManager.GetString("RBusView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Log.
        /// </summary>
        public static string ShowLogView {
            get {
                return ResourceManager.GetString("ShowLogView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System State - Full.
        /// </summary>
        public static string SystemStateFullView {
            get {
                return ResourceManager.GetString("SystemStateFullView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System state.
        /// </summary>
        public static string SystemStateView {
            get {
                return ResourceManager.GetString("SystemStateView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving data for key &apos;{key}&apos;: {ex.Message}.
        /// </summary>
        public static string Text0001 {
            get {
                return ResourceManager.GetString("Text0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading data for key &apos;{key}&apos;: {ex.Message}.
        /// </summary>
        public static string Text0002 {
            get {
                return ResourceManager.GetString("Text0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to open manual. Selected file: {FileName}.
        /// </summary>
        public static string Text0003 {
            get {
                return ResourceManager.GetString("Text0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual file not found at path: {FilePath}.
        /// </summary>
        public static string Text0004 {
            get {
                return ResourceManager.GetString("Text0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open the user manual: {Message}.
        /// </summary>
        public static string Text0005 {
            get {
                return ResourceManager.GetString("Text0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turnouts.
        /// </summary>
        public static string TurnoutListView {
            get {
                return ResourceManager.GetString("TurnoutListView", resourceCulture);
            }
        }
    }
}
